# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.Currency'),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.Currency'),
        ),
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.FloatField(default=None),
        ),
    ]
